#!/usr/bin/env bash

~/.fehbg &
keepassxc &
firefox-nightly &
alacritty &
discord &
thunderbird &
#redshift &
dunst -conf ~/.config/dunst/dunstrc &
mpd &
mpdas &
nm-applet &
compton &
ibus-daemon -drx &
~/.config/polybar/launch.sh &
transmission-gtk
#cadence-session-start --system-start &
#pulseeffects --gapplication-service

