#!/usr/bin/env bash

#~/bin/start_jack &
~/.fehbg &
keepassxc &
firefox &
alacritty &
discord &
thunderbird &
redshift &
dunst -conf ~/.config/dunst/dunstrc &
mpd &
mpdas &
nm-applet &
picom &
ibus-daemon -drx &
~/.config/polybar/launch.sh &
~/.config/polybar/scripts/spotify_status.py &
zeal &
sxhkd

