#!/usr/bin/env bash

#~/bin/start_jack &
~/.fehbg &
keepassxc &
firefox-nightly &
alacritty &
discord &
thunderbird &
redshift &
dunst -conf ~/.config/dunst/dunstrc &
mpd &
mpdas &
nm-applet &
picom &
ibus-daemon -drx &
~/.config/polybar/launch.sh &
transmission-daemon &
cadence-session-start --system-start &
~/.config/polybar/scripts/spotify/py_spotify_listener.py &
zeal &
sxhkd &

