#! /bin/sh

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#bspc config normal_border_color "#$color8"
#bspc config active_border_color "#$color9"
#bspc config focused_border_color "#$color9"
bspc config presel_feedback_color "#$color1"

bspc config normal_border_color "#B0FFEE"
bspc config focused_border_color "#FFB0C1"

bspc rule -a Firefox:\* desktop='^2'
bspc rule -a discord:\* desktop='^3'
bspc rule -a Spotify:\* desktop='^4'
bspc rule -a Steam:\* desktop='^5'
bspc rule -a Thunderbird: desktop='^6'
bspc rule -a Slack:\* desktop='^7'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Deluge desktop='^9'
bspc rule -a Transmission-gtk desktop='^9'
bspc rule -a KeePassXC:\* state=floating
bspc rule -a mpv:\* state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Steam:'Friends List' state=floating
bcpc rule -a MultiMC5:\* state=floating
bcpc rule -a 'Minecraft Launcher*':\* state=floating
bcpc rule -a Zeal:\* state=floating

# Autostart
#sxhkd &
~/.config/bspwm/autostart

