#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export VISUAL='nvim'
export EDITOR=$VISUAL
export PAGER='less'

#
# Language
#

#
# Paths
#
export PATH=$PATH:~/bin
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/opt/local/bin:/opt/local/sbin
export PATH=$PATH:~/.local/bin/
export PATH=$PATH:~/.gem/ruby/2.6.0/bin

export PATH=$PATH:~/dotfiles/extra/utility
export PATH=$PATH:~/dotfiles/extra/executor
export PATH=~/venv/bin:$PATH
export PATH="/home/aquamarine/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath PATH

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_HOME
export HISTFILE="~/.zhistory"

xrdb -merge /home/aquamarine/.Xresources

source /home/aquamarine/websites

