HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Customize to your needs...
alias c="clear"
alias ls='ls --color=auto'
alias la="ls -la"
alias fetch="neofetch"
alias shutdown="sudo poweroff"
alias logoff="sudo pkill -u aquamarine"
alias vi="nvim"
alias vim="nvim"
alias memcheck="valgrind --leak-check=full --show-reachable=yes"
alias mpd="mpd ~/.config/mpd/mpd.conf"
alias wrpi="mpv http://icecast1.wrpi.org:8000/mp3-320.mp3"
alias pro="cd ~/Programming"
alias open="xdg-open"
alias dsrc="ssh $DSERVER"
#alias yay="yay --editmenu --nodiffmenu --save"
#alias dock="sudo docker build -t=mcsema . && sudo docker run --rm -it --ipc=host -v "${PWD}":/home/user/local mcsema"

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

export VISUAL='nvim'
export EDITOR=$VISUAL
export PAGER='less'

# other exports
export obfus='/home/aquamarine/vbox shared/obfuscator/lib/Transforms/Obfuscation/'
export QT_QPA_PLATFORMTHEME='qt5ct'

# color for less and man
export MANPAGER='less -s -M +Gg'
export LESS="--RAW-CONTROL-CHARS"
lesscolors=$HOME/bin/.LESS_TERMCAP
[[ -f $lesscolors ]] && . $lesscolors

# PATH
export PATH=$PATH:~/bin
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/opt/local/bin:/opt/local/sbin
export PATH=$PATH:~/.local/bin/
export PATH=$PATH:~/.gem/ruby/2.6.0/bin

export PATH=$PATH:~/dotfiles/extra/utility
export PATH=$PATH:~/dotfiles/extra/executor
export PATH=~/venv/bin:$PATH
export PATH="/home/aquamarine/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#PROMPT='%F{green}%B%c%b%f '
export GPG_TTY=$(tty)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# set title on terminal spawn
precmd () {
    print -Pn "\e]0;%~\a"
}

autoload -U promptinit; promptinit
prompt pure

autoload -U compinit
compinit

export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

