# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Customize to your needs...
alias c='clear'
alias ls='ls --color=auto'
alias la='ls -la'
alias fetch='neofetch'
alias shutdown='sudo poweroff'
alias logoff='sudo pkill -u aquamarine'
alias vi='nvim'
alias vim='nvim'
alias memcheck='valgrind --leak-check=full --show-reachable=yes'
alias mpd='mpd ~/.config/mpd/mpd.conf'
alias wrpi='mpv --no-resume-playback http://icecast1.wrpi.org:8000/mp3-320.mp3'
alias open='xdg-open'
alias zathura="zathura -c --fork ~/.config/zathura/zathurarc"
alias virtualcam='ffmpeg -f x11grab -r 15 -s 1920x1080 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0'
alias ssh='TERM=xterm-256color ssh'
#alias yay="yay --editmenu --nodiffmenu --save"
#alias dock="sudo docker build -t=mcsema . && sudo docker run --rm -it --ipc=host -v "${PWD}":/home/user/local mcsema"

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

export VISUAL='nvim'
export EDITOR=$VISUAL
export PAGER='less'

# other exports
export FZF_DEFAULT_COMMAND='ag -u -g ""'

# color for less and man
export MANPAGER='less -s -M +Gg'
export LESS="--RAW-CONTROL-CHARS"
lesscolors=$HOME/bin/.LESS_TERMCAP
[[ -f $lesscolors ]] && . $lesscolors

# PATH
export PATH=~/bin:$PATH
export PATH=~/.cargo/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/opt/local/bin:/opt/local/sbin
export PATH=$PATH:~/.local/bin/
export PATH=$PATH:/home/aquamarine/.gem/ruby/2.7.0/bin
export PATH=$PATH:/home/aquamarine/.pyenv/bin
#export PATH=/home/aquamarine/.pyenv/shims:$PATH

export XDG_DATA_DIRS=$XDG_DATA_DIRS:/var/lib/flatpak/exports/share
export XDG_DATA_DIRS=$XDG_DATA_DIRS:/home/aquamarine/.local/share/flatpak/exports/share

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export GPG_TTY=$(tty)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# set title on terminal spawn
precmd () {
    print -Pn "\e]0;%~\a"
}

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

autoload -U compinit
compinit

export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

unset SSH_ASKPASS

